apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-service-name" . }}
  labels:
    {{- include "r1-nginx.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.jmx }}
      targetPort: jmx
      protocol: TCP
      name: jmx
  selector:
    {{- include "r1-nginx.selectorLabels" . | nindent 4 }}
