strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 3
    maxUnavailable: 1
image:
  image_registry: acrargopogwizdow.azurecr.io/
  image_repository: r2.nginx
  environment: preprod-
  version_major: '1'
  version_minor: '2'
  version_patch: 120ee88
  pullPolicy: Always
serviceAccount:
  name: r2-nginx
labels:
  tier: front
service:
  type: ClusterIP
  port: 80
  targetPort: 80
