strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 3
    maxUnavailable: 1
image:
  image_registry: acrargopogwizdow.azurecr.io
  image_repository: r2.nginx
  environment: dev-
  version_major: '1'
  version_minor: '3'
  version_patch: bcbbf99
  pullPolicy: Always
serviceAccount:
  name: sa-dev-r2-nginx
service:
  type: ClusterIP
  port: 80
  targetPort: 80
