strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 3
    maxUnavailable: 1
image:
  image_registry: acrargopogwizdow.azurecr.io
  image_repository: r2.nginx
  environment: prod-
  version_major: '1'
<<<<<<< HEAD
  version_minor: '3'
  version_patch: 73e21f0
=======
  version_minor: '0'
  version_patch: '0'
>>>>>>> ae1663fbf723f76a06740eeaaab494fc7e5151aa
  pullPolicy: Always

serviceAccount:
  name: sa-prod-r2-nginx
<<<<<<< HEAD
=======

>>>>>>> ae1663fbf723f76a06740eeaaab494fc7e5151aa
service:
  type: ClusterIP
  port: 80
  targetPort: 80