strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 3
    maxUnavailable: 1
image:
  image_registry: acrargopogwizdow.azurecr.io
  image_repository: r2.nginx
  environment: preprod-
  version_major: '1'
<<<<<<< HEAD
  version_minor: '4'
  version_patch: 448713f
=======
  version_minor: '0'
  version_patch: '0'
>>>>>>> 10fb87ec4606a48ffa5c1eb4cac8df0d0274c554
  pullPolicy: Always

serviceAccount:
  name: sa-preprod-r2-nginx

service:
  type: ClusterIP
  port: 80
  targetPort: 80