strategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 3
    maxUnavailable: 1
image:
  image_registry: acrargopogwizdow.azurecr.io
  image_repository: r2.nginx
  environment: prod-
  version_major: '1'
  version_minor: '4'
  version_patch: 448713f
  pullPolicy: Always
serviceAccount:
  name: sa-prod-r2-nginx
service:
  type: ClusterIP
  port: 80
  targetPort: 80
